# docker-compose.yml
version: "3.1"
services: 
  server:
    build: ./server
    depends_on:
      - postgres
    ports: 
      - "3001:3001"

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: practicedocker
      POSTGRES_PASSWORD: practicedocker
      POSTGRES_DB: practicedocker

  adminer: 
    image: adminer
    restart: always
    ports: 
      - 2020:2020
  
  client:
    build: ./client
    ports: 
      - 8080:8080
    depends_on: 
      - server
#    volumes:
#      - ./server:/usr/src/app
#    ports:
#      - 3001:3001
#    depends_on:
#      - postgres
#    environment: 
#      DATABASE_URL: postgres://postgres@postgres/20-questions
#  postgres:
#    image: postgres:12
#    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: 20-questions

