# docker-compose.yml
version: "3.1"
services: 
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  adminer: 
    image: adminer
    restart: always
    ports: 
      - "2020:2020"
  
  client:
    build: ./client
    ports: 
      - "8080:8080"
    depends_on: 
      - server

  server:
    build: ./server
    depends_on:
      - postgres
    links:
      - postgres
    ports: 
      - "3001:3001"